/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blood.bank.management.system;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Navnath Gunjal
 */
public class BloodDoanar extends javax.swing.JFrame {
private Connection connection = null;
    public BloodDoanar() {
        
        initComponents();
        ImageIcon icon2 = new ImageIcon(Toolkit.getDefaultToolkit().createImage(getClass().getResource("about.png")));
        Image img2 = icon2.getImage();
        Image newImage2 = img2.getScaledInstance(donarhomeimage.getWidth(),donarhomeimage.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon newImageIcon2 = new ImageIcon(newImage2);
        donarhomeimage.setIcon(newImageIcon2);
    try {
        ShowProfile();
    } catch (SQLException ex) {
        Logger.getLogger(BloodDoanar.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        donarhomeimage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        Avaliablebloodtable = new javax.swing.JTable();
        BloodDonarPrint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        donarinsert = new javax.swing.JButton();
        donardelete = new javax.swing.JButton();
        Donnarid = new javax.swing.JTextField();
        donarbottels = new javax.swing.JComboBox<>();
        donarbloodgroup = new javax.swing.JComboBox<>();
        donarcity = new javax.swing.JComboBox<>();
        donarname = new javax.swing.JTextField();
        Donarbloodbankname = new javax.swing.JTextField();
        Dateofdonation = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        Donationtable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        Profiletable = new javax.swing.JTable();
        BloodDonarLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Closemenubar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("                                                     Blood Donation Interface");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("                                                              Donate Blood Save Life!");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 0), new java.awt.Color(0, 204, 204), new java.awt.Color(153, 0, 153), new java.awt.Color(51, 0, 51)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
            .addComponent(donarhomeimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(donarhomeimage, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Home", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));

        Avaliablebloodtable.setBackground(new java.awt.Color(51, 255, 204));
        jScrollPane10.setViewportView(Avaliablebloodtable);

        BloodDonarPrint.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BloodDonarPrint.setForeground(new java.awt.Color(255, 51, 0));
        BloodDonarPrint.setText("Print");
        BloodDonarPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodDonarPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 907, Short.MAX_VALUE)
                .addComponent(BloodDonarPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BloodDonarPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 49, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane2.addTab("Avaliable Blood", jPanel2);

        jPanel8.setBackground(new java.awt.Color(51, 255, 204));

        jLabel31.setBackground(java.awt.Color.red);
        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setText("User ID");

        jLabel32.setBackground(java.awt.Color.red);
        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel32.setText("User Name");

        jLabel33.setBackground(java.awt.Color.red);
        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel33.setText("Blood Bank Name");

        jLabel34.setBackground(java.awt.Color.red);
        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel34.setText("City");

        jLabel35.setBackground(java.awt.Color.red);
        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel35.setText("Blood Group");

        jLabel36.setBackground(java.awt.Color.red);
        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel36.setText("Bottels");

        jLabel37.setBackground(java.awt.Color.red);
        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel37.setText("Date Of Donation");

        donarinsert.setBackground(java.awt.Color.red);
        donarinsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        donarinsert.setText("Insert");
        donarinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donarinsertActionPerformed(evt);
            }
        });

        donardelete.setBackground(java.awt.Color.red);
        donardelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        donardelete.setText("Delete");
        donardelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donardeleteActionPerformed(evt);
            }
        });

        Donnarid.setBackground(java.awt.Color.yellow);

        donarbottels.setBackground(java.awt.Color.red);
        donarbottels.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        donarbloodgroup.setBackground(java.awt.Color.red);
        donarbloodgroup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        donarbloodgroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Positive(A+)", "A Negative(A-)", "B Positive(B+)", "B Negative(B-)", "AB Positive(AB+)", "AB Negative(AB-)", "O Positive(O+)", "O Negative (O-)", " " }));

        donarcity.setBackground(java.awt.Color.red);
        donarcity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        donarcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shirdi", "Rahata", "Loni", "Kopergaon", "Sangmner", "Shrirampur", "Ahmednagar" }));

        donarname.setBackground(java.awt.Color.yellow);

        Donarbloodbankname.setBackground(java.awt.Color.yellow);
        Donarbloodbankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonarbloodbanknameActionPerformed(evt);
            }
        });

        Dateofdonation.setBackground(java.awt.Color.yellow);
        Dateofdonation.setText("DD/MM/YY");

        Donationtable.setBackground(java.awt.Color.red);
        jScrollPane8.setViewportView(Donationtable);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(donarinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(75, 75, 75))
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(donarname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Donarbloodbankname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(donarcity, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE)
                    .addComponent(donarbloodgroup, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE)
                    .addComponent(donarbottels, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dateofdonation, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(donardelete, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addComponent(Donnarid))
                .addGap(68, 68, 68)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Donnarid, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(donarname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Donarbloodbankname)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(donarcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(donarbloodgroup))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donarbottels)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Dateofdonation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donarinsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(donardelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Make Donation", jPanel4);

        jScrollPane11.setViewportView(Profiletable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Profile", jPanel9);

        BloodDonarLogout.setBackground(new java.awt.Color(51, 255, 204));
        BloodDonarLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BloodDonarLogout.setForeground(new java.awt.Color(255, 51, 0));
        BloodDonarLogout.setText("Logout");
        BloodDonarLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodDonarLogoutActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(51, 255, 204));

        jMenu1.setText("Open");

        Closemenubar.setText("Close");
        Closemenubar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosemenubarActionPerformed(evt);
            }
        });
        jMenu1.add(Closemenubar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        jMenu2.add(Help);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BloodDonarLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(BloodDonarLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    private void ClosemenubarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosemenubarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ClosemenubarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      Donnarid.setText(MainForm.getId());
      
    }//GEN-LAST:event_formWindowActivated

    private void DonarbloodbanknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonarbloodbanknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonarbloodbanknameActionPerformed

    private void donarinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donarinsertActionPerformed
            try{
          connection = DatabaseConnection.dataBaseconnection();
     }catch(Exception ex)
     {
         JOptionPane.showMessageDialog(null,ex.getMessage());
     }
     
            try
        {
            Statement st = connection.createStatement();
            String query = "insert into donardetails values('"+Integer.parseInt(Donnarid.getText())+"','"+donarname.getText()+"','"+Donarbloodbankname.getText()+"','"+donarcity.getSelectedItem()+"','"+donarbloodgroup.getSelectedItem()+"','"+donarbottels.getSelectedItem()+"','"+Dateofdonation.getText()+"')";
        st.executeUpdate(query);
       JOptionPane.showMessageDialog(null,"Donar Data Inserted");
       try
    {
        Statement st1 = connection.createStatement();
        String query1 = "select * from donardetails where id = '"+Integer.parseInt(Donnarid.getText())+"'";
        ResultSet rs1 = st1.executeQuery(query1);
        Donationtable.setModel(DbUtils.resultSetToTableModel(rs1));
        
    }catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }
        }catch(HeadlessException | NumberFormatException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }finally
                {
                    try
        {
            connection.close();
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
                }
    }//GEN-LAST:event_donarinsertActionPerformed

    private void donardeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donardeleteActionPerformed
         try {
        connection = DatabaseConnection.dataBaseconnection();
    } catch (InstantiationException ex) {
        Logger.getLogger(BloodDoanar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(BloodDoanar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(BloodDoanar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(BloodDoanar.class.getName()).log(Level.SEVERE, null, ex);
    }
    try
    {
        Statement st = connection.createStatement();
        String query = "delete from donardetails where id='"+Integer.parseInt(Donnarid.getText())+"'";
       JOptionPane.showMessageDialog(null,"Your Record deleted Successfully!");
       
    }catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }
    finally
    {
        try
        {
            connection.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }
    }//GEN-LAST:event_donardeleteActionPerformed

    private void BloodDonarLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodDonarLogoutActionPerformed
       dispose();
       new MainForm().show();
    }//GEN-LAST:event_BloodDonarLogoutActionPerformed

    private void BloodDonarPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodDonarPrintActionPerformed
        MessageFormat header = new MessageFormat("This is record");
        MessageFormat footer = new MessageFormat("Please Find Attachments");
        try
        {
            Avaliablebloodtable.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_BloodDonarPrintActionPerformed
 public void ShowProfile() throws SQLException
{
    try {
        connection = DatabaseConnection.dataBaseconnection();
    } catch (InstantiationException ex) {
        Logger.getLogger(BloodDoanar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(BloodDoanar.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(BloodDoanar.class.getName()).log(Level.SEVERE, null, ex);
    }
    try
    {
        Statement st = connection.createStatement();
        String query = "select * from userdetails where id ='"+Integer.parseInt(MainForm.getId())+"'";
        ResultSet rs = st.executeQuery(query);
        Profiletable.setModel(DbUtils.resultSetToTableModel(rs));
            
    }catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }
    try
    {
        Statement st2 = connection.createStatement();
        String query2 = "select * from donardetails";
        ResultSet rs2 = st2.executeQuery(query2);
       Avaliablebloodtable.setModel(DbUtils.resultSetToTableModel(rs2));
        
    }catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }
    finally
    {
         try
    {
     connection.close();
    }catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }
    }
    
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodDoanar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodDoanar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodDoanar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodDoanar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodDoanar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Avaliablebloodtable;
    private javax.swing.JButton BloodDonarLogout;
    private javax.swing.JButton BloodDonarPrint;
    private javax.swing.JMenuItem Closemenubar;
    private javax.swing.JTextField Dateofdonation;
    private javax.swing.JTextField Donarbloodbankname;
    private javax.swing.JTable Donationtable;
    private javax.swing.JTextField Donnarid;
    private javax.swing.JMenuItem Help;
    private javax.swing.JTable Profiletable;
    private javax.swing.JComboBox<String> donarbloodgroup;
    private javax.swing.JComboBox<String> donarbottels;
    private javax.swing.JComboBox<String> donarcity;
    private javax.swing.JButton donardelete;
    private javax.swing.JLabel donarhomeimage;
    private javax.swing.JButton donarinsert;
    private javax.swing.JTextField donarname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
